name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Pack
      run: dotnet pack ./QwQ.Console/QwQ.Console.fsproj --no-build -c Release

    - name: Upload
      uses: actions/upload-artifact@v2.2.4
      with:
        name: QwQ Console Nuget Package
        path: ./QwQ.Console/bin/Release/*.nuget

        
