name: Full Test

on: [ workflow_dispatch ]

jobs:
  list-posts:
  
    name: list-posts

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        source: 
          - 'Konachan'
          - 'Yandere'
          - 'Lolibooru'
          - 'HypnoHub'
          - 'Danbooru'
          - 'ATFBooru'
          - 'Sonohara'
          - 'Hijiribe'
          - 'Safebooru Donmai'
          - 'Gelbooru'
        # - 'The Big ImageBoard (TBIB)'
        # - 'Safebooru'
          - 'XBooru'
          - 'Rule34'
          - 'Sankaku Channel'
          - 'Idol Complex'
          - 'All Girl'
          - 'Foot Fetish Booru'
          - 'CGBooru'
          - 'Touhou'
          - 'Anime Girls 2020'
          - 'Character Library'
          - 'Ecchi Booru'
          - 'Hina'
          - 'RuleXXX'
          - 'Nekobooru'
          - 'Tentacle Rape'
          - 'Fan Service'
          - 'Rule34 Paheal'
          - 'NHentai'
        # - 'Nozomi'
        # - 'Lolibaka'
          - 'Booru.io'

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: List All Posts
      run: dotnet fsi FullTest.fsx "${{ matrix.source }}" --list-posts
      
      
  list-tags:
    name: list-tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: 
          - 'Konachan'
          - 'Yandere'
          - 'Lolibooru'
          - 'HypnoHub'
          - 'Danbooru'
          - 'ATFBooru'
        # - 'Sonohara'
          - 'Hijiribe'
          - 'Safebooru Donmai'
          - 'Gelbooru'
        # - 'The Big ImageBoard (TBIB)'
          - 'Safebooru'
          - 'XBooru'
          - 'Rule34'
        # - 'Sankaku Channel'
          - 'Idol Complex'
          - 'Nekobooru'
          - 'Tentacle Rape'
          - 'Fan Service'

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Test
      run: dotnet fsi FullTest.fsx "${{ matrix.source }}" --list-tags
      

    
