name: Full Test

on: [ workflow_dispatch ]

jobs:
  build:
  
    name: full-test

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        source: 
          - 'Konachan'
          - 'Yandere'
          - 'Lolibooru'
          - 'HypnoHub'
          - 'Danbooru'
          - 'ATFBooru'

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet publish ./QwQ/QwQ.fsproj -c Release -f netstandard2.0
      
    - name: Full Test
      run: dotnet fsi FullTest.fsx ${{ matrix.source }}
      
      
