name: Full Test

on: [ workflow_dispatch ]

jobs:
  build:
  
    name: full-test

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        source: 
          - 'Konachan'
          - 'Yandere'
          - 'Lolibooru'
          - 'HypnoHub'
          - 'Danbooru'
          - 'ATFBooru'
          - 'Sonohara'
          - 'Hijiribe'
          - 'Gelbooru'
          - 'The Big ImageBoard (TBIB)'
          - 'Safebooru'
          - 'XBooru'
          - 'Rule34'
          - 'Sankaku Channel'
          - 'Idol Complex'

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet publish ./QwQ/QwQ.fsproj -c Release -f netstandard2.0

    - name: Test All Tags
      run: dotnet fsi FullTest.fsx "${{ matrix.source }}" --list-posts
      
    - name: Test All Posts
      run: dotnet fsi FullTest.fsx "${{ matrix.source }}" --list-tags
      
    